export const USER_REQUEST="USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";

export const ADMIN_USER_DELETE_REQUEST = "ADMIN_USER_DELETE_REQUEST";
export const ADMIN_USER_DELETE_SUCCESS = " ADMIN_USER_DELETE_SUCCESS";
export const ADMIN_USER_DELETE_FAILURE = "ADMIN_USER_DELETE_FAILURE";